### PR TITLE
Implement Tools / Actions in the component

### LINKED ISSUE #4: Implement Tools / Actions in the component
Mendable.ai just launched a feature called tools and actions that allows the AI to use tools to complete a task. (An action is essentially the same as a tool but we differentiate it in the UI)

Simple Objective: **The goal here would be to implement the loading states for when the AI is loading tools, is using a tool or had a tool error just like we have in our components.**

All we need to is to capture the below stream events and present that nicely to the users when the AI is loading/using a tool:

Feel free to use this Mendable anon_key for testing `25f4cba6-f997-4991-bf4f-dbb5fab8f7bd`

and here is query you can use to test tools `What's the weather in SF right now?` - it will cache the responses if you test too fast, so modify the query accordingly.

**Here is the API for the streaming of tools:**

Chunk <|loading_tools|> only shows if "Tools and Actions" is enabled. That chunk will contain "true" if AI is looking for tools to take action on the user's request.

Chunk <|tool_called|> only shows if "Tools and Actions" is enabled. That chunk will contain an object with the name of the tool that was called and a `is_action` boolean. {name: tool_name , is_action: true/false}.

Chunk <|tool_error|> only shows if "Tools and Actions" is enabled. That chunk will contain a string with the error message.

Reference can be found here: 
https://docs.mendable.ai/mendable-api/chat#stream-response
https://docs.mendable.ai/tools#using-via-api

Here is a reference UI component that we use for our other components. Feel free to use it/adapt it to make the UI similar

```
import React from "react";
import { AiOutlineTool, AiOutlineWarning } from "react-icons/ai";
import { CgSpinner } from "react-icons/cg";
import { MendableTool } from "../../types";
import { BsLightningCharge } from "react-icons/bs";

export default function UsingTool({
  loading,
  error,
  currentTool,
  className,
}: {
  loading: boolean;
  error?: string;
  currentTool: MendableTool;
  className?: string;
}) {
  return (
    <div
      onClick={() => {
        if (error) {
          alert(error);
        }
      }}
      title={error ?? "Using " + currentTool.name + " Tool"}
      className={
        `${className} ms-flex ms-w-fit ms-items-center ms-rounded-md ms-border ms-px-2 ms-py-[5px] ms-text-xs hover:ms-cursor-pointer` +
        (error
          ? " ms-border-orange-500 ms-bg-orange-500/25 ms-text-orange-500"
          : currentTool.is_action
          ? " ms-border-yellow-400 ms-bg-yellow-400/25 ms-text-yellow-400"
          : " ms-border-primary ms-bg-primary/25 ms-text-primary")
      }
    >
      {loading ? (
        <CgSpinner className="ms-mr-1 ms-animate-spin" size={20} />
      ) : error ? (
        <AiOutlineWarning className="ms-mr-1" size={20} />
      ) : currentTool.is_action ? (
        <BsLightningCharge
          className="ms-mr-1 ms-fill-yellow-400"
          size={18}
        />
      ) : (
        <AiOutlineTool className="ms-mr-1" size={20} />
      )}
      {currentTool.name} {!currentTool.is_action ? "Tool" : ""}
    </div>
  );
}
```

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #4 
/claim #4

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@nickscamara 

Can you check this out locally?

The loading indicators have been replaced, would want your review and changes as to what's the expectation in terms of design.

**Comment by nickscamara** [comment]
Hey @rishi-raj-jain , nice trick you did there with the parsing! 

But the loading animation doesn't seem to work for me. And yea I also would prefer if the component that I gave to you was used (at least the whole design + animation from it). Can you also make sure that the loading tools icons go away after the tool has finished? Thank you!

**Comment by rishi-raj-jain** [comment]
Hey @nickscamara,

Oh I see the component you shared was using custom classes and margin. I replaced them with tailwind specific classes. Now loading animation shall work.

> at least the whole design + animation from it

Actually, this part is what I can't see as the component uses custom classes 😅

> Can you also make sure that the loading tools icons go away after the tool has finished?

Handled this part as well.

**Comment by nickscamara** [comment]
Thanks @rishi-raj-jain  the animation works now! Gotcha - sorry. Don't worry about the styling too much anymore then, I can tweak that with our classes. The only thing left now is:

- We need to be able to display the tool name that is being used which comes from the chunk that was streamed. You might need to modify the stream code:

Chunk <|tool_called|> only shows if "Tools and Actions" is enabled. That chunk will contain an object inside the `metadata` property with the name of the tool that was called and a is_action boolean. metadata {name: tool_name , is_action: true/false}. 

If is_action is true inside there we need to use a lightning bolt instead of the tool icon.

Once this works, it should be good!

**Comment by rishi-raj-jain** [comment]
@nickscamara 

This is ready for your review with all changes.

**Comment by nickscamara** [comment]
Looks good! Thank you! @rishi-raj-jain

**Comment by rishi-raj-jain** [comment]
> Looks good! Thank you! @rishi-raj-jain

Pleasure!

**Pull request merged**
